### ISSUE TITLE
mdx

### ISSUE THREAD

**Issue by pzzyf** [Magren0321/nerukigat#17]

**Comment by pzzyf** [comment]
你好，使用你这的博客当模板。请问作者是怎么预览mdx的，下了几个插件去预览效果不太好，本地启动写一下看一下又太麻烦了，请问作者是怎么弄的。

**Comment by Magren0321** [comment]
> 你好，使用你这的博客当模板。请问作者是怎么预览mdx的，下了几个插件去预览效果不太好，本地启动写一下看一下又太麻烦了，请问作者是怎么弄的。

我这边也只是用mdx preview在写的时候看markdown语法有没有生效，然后具体样式效果还是得本地启动看

**Comment by pzzyf** [comment]
i know
